spring:
  datasource:
    #url: jdbc:mysql://114.55.37.2:3306/luntan?allowMultiQueries=true&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/luntan?allowMultiQueries=true&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: mzx123
    # 禁用模板引擎的缓存
    type: com.alibaba.druid.pool.DruidDataSource

    #   数据源其他配置(默认不起作用)
    # 定义初始连接数
    initialSize: 5
    # 定义最小空闲数
    minIdle: 5
    # 定义最大连接数
    maxActive: 20
    # 定义最大空闲数
    maxWait: 60000
    # 执行validationQuery检测连接是否有效。默认值为false
    timeBetweenEvictionRunsMillis: 60000
    # 链接保持空闲而不被驱逐的最小时间  evict 驱逐
    minEvictableIdleTimeMillis: 300000
    #  检测链接是否有效的SQL 语句
    validationQuery: SELECT 1 FROM DUAL
    # 建议配置true   不影响性能 并且保证安全性 申请链接时执行如果空闲时间大于min的空闲时间执行查询语句看连接是否有效
    testWhileIdle: true
    #  申请链接时执行 validationQuery  检测链接是否有效 做了配置性能降低
    testOnBorrow: true
    # 归还链接时执行 validationQuery 检测链接是否有效  配置会降低
    testOnReturn: true
    # 是否缓存preparedStatements   也就是 PSCache  PSCache对支持游标数据库的性能提升最大   mysql下建议关闭
    poolPreparedStatements: false
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    # 针对单个connection 链接
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置公用监测数据
    useGlobalDataSourceStat: true
    #
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.myboot07.bean


